# Generated by Django 5.0.2 on 2024-03-01 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnumeratedWebsites',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('a_text', models.TextField(blank=True, null=True)),
                ('a_href_text', models.TextField(blank=True, null=True)),
                ('img_src_text', models.TextField(blank=True, null=True)),
                ('img_alt_text', models.TextField(blank=True, null=True)),
                ('h1_text', models.TextField(blank=True, null=True)),
                ('h2_text', models.TextField(blank=True, null=True)),
                ('h3_text', models.TextField(blank=True, null=True)),
                ('h4_text', models.TextField(blank=True, null=True)),
                ('h5_text', models.TextField(blank=True, null=True)),
                ('h6_text', models.TextField(blank=True, null=True)),
                ('div_text', models.TextField(blank=True, null=True)),
                ('p_text', models.TextField(blank=True, null=True)),
                ('span_text', models.TextField(blank=True, null=True)),
                ('b_text', models.TextField(blank=True, null=True)),
                ('strong_text', models.TextField(blank=True, null=True)),
                ('cite_text', models.TextField(blank=True, null=True)),
                ('blockquote_text', models.TextField(blank=True, null=True)),
                ('ul_text', models.TextField(blank=True, null=True)),
                ('ol_text', models.TextField(blank=True, null=True)),
                ('li_text', models.TextField(blank=True, null=True)),
                ('nav_ul_li_text', models.TextField(blank=True, null=True)),
                ('last_enumerated', models.DateTimeField(auto_now_add=True)),
                ('emails', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnionLinks',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=100)),
                ('source_url', models.URLField()),
                ('visited', models.BooleanField()),
                ('keyword_searched', models.CharField(max_length=20)),
                ('date_searched', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('thread_url', models.URLField(primary_key=True, serialize=False)),
                ('thread_title', models.TextField(blank=True, null=True)),
                ('thread_desc', models.TextField(blank=True, null=True)),
                ('thread_author', models.TextField(blank=True, null=True)),
                ('thread_published', models.DateTimeField(blank=True, null=True)),
                ('enumerated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ThreadComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_author', models.TextField()),
                ('comment_author_title', models.TextField()),
                ('comment_date', models.DateTimeField(blank=True, null=True)),
                ('thread_url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dti.threads')),
            ],
        ),
    ]
