# Generated by Django 5.0.7 on 2024-07-22 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnumeratedWebsites',
            fields=[
                ('website_id', models.IntegerField(null=True, unique=True)),
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('a_text', models.TextField(blank=True, null=True)),
                ('a_href_text', models.TextField(blank=True, null=True)),
                ('img_src_text', models.TextField(blank=True, null=True)),
                ('img_alt_text', models.TextField(blank=True, null=True)),
                ('h1_text', models.TextField(blank=True, null=True)),
                ('h2_text', models.TextField(blank=True, null=True)),
                ('h3_text', models.TextField(blank=True, null=True)),
                ('h4_text', models.TextField(blank=True, null=True)),
                ('h5_text', models.TextField(blank=True, null=True)),
                ('h6_text', models.TextField(blank=True, null=True)),
                ('div_text', models.TextField(blank=True, null=True)),
                ('p_text', models.TextField(blank=True, null=True)),
                ('span_text', models.TextField(blank=True, null=True)),
                ('b_text', models.TextField(blank=True, null=True)),
                ('strong_text', models.TextField(blank=True, null=True)),
                ('cite_text', models.TextField(blank=True, null=True)),
                ('blockquote_text', models.TextField(blank=True, null=True)),
                ('ul_text', models.TextField(blank=True, null=True)),
                ('ol_text', models.TextField(blank=True, null=True)),
                ('li_text', models.TextField(blank=True, null=True)),
                ('nav_ul_li_text', models.TextField(blank=True, null=True)),
                ('last_enumerated', models.DateTimeField(auto_now_add=True)),
                ('emails', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.TextField()),
                ('img_path', models.CharField(max_length=1024)),
                ('img_url', models.URLField()),
                ('img_alt_text', models.TextField()),
                ('gps_version_ide', models.TextField()),
                ('latitude_reference', models.CharField(max_length=5)),
                ('latitude', models.CharField(max_length=15)),
                ('longitude_reference', models.CharField(max_length=5)),
                ('longitude', models.CharField(max_length=15)),
                ('altitude_reference', models.CharField(max_length=5)),
                ('altitude', models.CharField(max_length=15)),
                ('datetime', models.DateTimeField()),
                ('cam_make', models.TextField()),
                ('cam_model', models.TextField()),
                ('cam_software', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OnionLinks',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=100)),
                ('source_url', models.URLField()),
                ('visited', models.BooleanField()),
                ('keyword_searched', models.CharField(default=None, max_length=20, null=True)),
                ('date_searched', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Threads',
            fields=[
                ('thread_url', models.URLField(primary_key=True, serialize=False)),
                ('thread_title', models.TextField(blank=True, null=True)),
                ('thread_desc', models.TextField(blank=True, null=True)),
                ('thread_author', models.TextField(blank=True, null=True)),
                ('thread_published', models.DateTimeField(blank=True, null=True)),
                ('enumerated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DarkwebUsers',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_email', models.TextField(blank=True, null=True)),
                ('user_phone', models.TextField(blank=True, null=True)),
                ('user_title', models.TextField(blank=True, null=True)),
                ('associated_website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dti.enumeratedwebsites')),
            ],
        ),
        migrations.CreateModel(
            name='CryptocurrencyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=100)),
                ('amount_in_crypto', models.FloatField()),
                ('amount_in_usd', models.FloatField()),
                ('transaction_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('associated_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dti.enumeratedwebsites')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoAddress',
            fields=[
                ('crypto_address', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('associated_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dti.enumeratedwebsites')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_author', models.TextField()),
                ('comment_author_title', models.TextField()),
                ('comment_date', models.DateTimeField(blank=True, null=True)),
                ('thread_url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dti.threads')),
            ],
        ),
        migrations.CreateModel(
            name='UserGoogleDork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_title', models.TextField()),
                ('result_description', models.TextField()),
                ('result_link', models.TextField()),
                ('query_string', models.TextField()),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dti.darkwebusers')),
            ],
        ),
    ]
