# Generated by Django 5.0.2 on 2024-03-02 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAddress',
            fields=[
                ('crypto_address', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('associated_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dti.enumeratedwebsites')),
            ],
        ),
        migrations.CreateModel(
            name='CryptocurrencyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=100)),
                ('amount_in_crypto', models.FloatField()),
                ('amount_in_usd', models.FloatField()),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('associated_website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dti.enumeratedwebsites')),
            ],
        ),
    ]
