# Generated by Django 5.0.2 on 2024-03-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dti', '0002_cryptoaddress_cryptocurrencytransaction_darkwebusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.TextField()),
                ('img_path', models.CharField(max_length=1024)),
                ('img_url', models.URLField()),
                ('img_alt_text', models.TextField()),
                ('gps_version_ide', models.TextField()),
                ('latitude_reference', models.CharField(max_length=5)),
                ('latitude', models.CharField(max_length=15)),
                ('longitude_reference', models.CharField(max_length=5)),
                ('longitude', models.CharField(max_length=15)),
                ('altitude_reference', models.CharField(max_length=5)),
                ('altitude', models.CharField(max_length=15)),
                ('datetime', models.DateTimeField()),
                ('cam_make', models.TextField()),
                ('cam_model', models.TextField()),
                ('cam_software', models.TextField()),
            ],
        ),
    ]
