# Generated by Django 5.0.2 on 2024-03-02 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dti', '0003_imagefiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarkwebUsers',
            fields=[
                ('user_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_email', models.TextField(blank=True, null=True)),
                ('user_phone', models.TextField(blank=True, null=True)),
                ('user_title', models.TextField(blank=True, null=True)),
                ('associated_website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dti.enumeratedwebsites')),
            ],
        ),
    ]
