# Generated by Django 5.0.2 on 2024-03-02 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dti', '0004_darkwebusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoogleDork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_title', models.TextField()),
                ('result_description', models.TextField()),
                ('result_link', models.TextField()),
                ('query_string', models.TextField()),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dti.darkwebusers')),
            ],
        ),
    ]
