# Generated by Django 5.0.2 on 2024-03-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dti', '0005_usergoogledork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrencytransaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
