# Generated by Django 5.0.2 on 2024-03-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dti', '0006_alter_cryptocurrencytransaction_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='enumeratedwebsites',
            name='website_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
